[context.production.environment]
  HUGO_VERSION = "0.26"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.26"

[[headers]]
  for = "/*"
  [headers.values]
    Ag-Auth-Dev = "*"
    X-Frame-Options = "DENY"